name: DrumPad

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: false
  xcodeVersion: "15.0"

fileGroups:
  - DrumPad

targets:
  DrumPad:
    type: application
    platform: iOS
    sources:
      - path: DrumPad
        excludes:
          - "*.md"
    dependencies:
      - sdk: Foundation.framework
    settings:
      base:
        INFOPLIST_FILE: DrumPad/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.example.DrumPad
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
